apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: personal-diary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: personal-diary-server:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: MODE
              value: K8S
            - name: MONGODB_SERVER
              value: mongodb-service.personal-diary
            - name: MONGODB_PORT
              value: '27017'
