apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: personal-diary
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
