apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
  namespace: personal-diary
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
