apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: personal-diary
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
