apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: personal-diary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: personal-diary-client:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
